[package]
name = "rust-crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
spider = "2.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
futures = "0.3"
html2md = "0.2"
slugify = "0.1" 